sudo: false
language: node_js
node_js:
  - "7.5.0"

notifications:
  email: evenchange4@gmail.com

script:
  - yarn run test
  - yarn run build

after_success:
  - ./node_modules/.bin/codecov --token=b55f4156-6bea-4f4a-a4ce-30dfff92bb8a

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master

cache:
  yarn: true
  directories:
    - node_modules
