sudo: false
language: node_js
node_js:
  - "6"
  - "7.5.0"
  - "7"

notifications:
  email: evenchange4@gmail.com

script:
  # - yarn run test
  - yarn run build

cache:
  yarn: true
  directories:
    - node_modules
