sudo: false
language: node_js
node_js:
  - "7.5.0"

notifications:
  email: evenchange4@gmail.com

script:
  - yarn run eslint
  - yarn run test
  - yarn run build

after_success:
  - ./node_modules/.bin/codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    tags: true

cache:
  yarn: true
  directories:
    - node_modules
